# Generated by Django 4.2 on 2024-12-16 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Номер телефона должен начинаться с 8 или +7, далее иметь 9 цифр', regex='^((\\+7)|8)9\\d{9}$')], verbose_name='Телефонный номер')),
                ('firstname', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('fathers_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('pasport', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='Паспорт должен быть в формате "<6_цифр><пробел><4_цифры>"', regex='^\\d{6} \\d{4}$')], verbose_name='Паспорт')),
                ('balance', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Баланс')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
