# Generated by Django 4.2 on 2024-12-15 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='pasport',
            field=models.CharField(validators=[django.core.validators.RegexValidator(code='Паспорт должен быть в формате "<6_цифр><пробел><4_цифры>"', regex='^\\d{6} \\d{4}$')], verbose_name='Паспорт'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Номер телефона должен начинаться с 8 или +7, далее иметь 9 цифр', regex='^((\\+7)|8)9\\d{9}$')], verbose_name='Телефонный номер'),
        ),
    ]
