# Generated by Django 4.2 on 2024-12-16 17:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='Место')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('duration', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Длительность (в часах)')),
            ],
            options={
                'verbose_name': 'Путевка',
                'verbose_name_plural': 'Путевки',
            },
        ),
        migrations.CreateModel(
            name='VoucherOffer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка')),
                ('status', models.CharField(choices=[('payed', 'Оплачено'), ('closed', 'Закрыто'), ('open', 'Открыто')], max_length=20)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_offers', to='firma.client', verbose_name='Клиент')),
                ('voucher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_offers', to='purchases.voucher', verbose_name='Путевка')),
            ],
            options={
                'verbose_name': 'Предложение путевки',
                'verbose_name_plural': 'Предложения путевок',
            },
        ),
    ]
